### PR TITLE
Halime pull request

### PR DESCRIPTION
**Pull request by Hlm-Sntrk**
Halime, I added 3 lines of comments.

### CODE REVIEW

**Comment by aysearifr** [comment]
oh it is great halime as you

**Comment by hamiltonthefirst** [comment]
This is from Jacob

**Comment by myusuf7** [comment]
Great job

**Comment by Cihatttt** [comment]
Good.

**Review by aysearifr — APPROVED** [review]
good job

**Review by hamiltonthefirst — APPROVED** [review]
Very good job. I believe :)

**Pull request merged**
